### ISSUE TITLE
[Bug] Select Albums and Singles Displaying Incorrect Thumbnails

### ISSUE THREAD

**Issue by UniOnTheMap** [prayag17/Blink#459]
**Describe the bug**
Specific albums and singles do not show their correct thumbnail, I've verified that it is a Blink issue by checking for if Jellyfin Web shows the thumbnail and it does.

**NOTE: In the first screenshot provided all of the albums/singles that do not have a thumbnail show one inside Jellyfin Web and is not specific to "Can You Feel My Heart"**

**To Reproduce**
1. Click on the Music page
2. Scroll down to the Album/Single
4. See visual bug
5. Click on the Album/Single
6. See that the thumbnail does not show on the side 

**Expected behavior**
It should show the thumbnail in the Music tab and when you click on it.

**Screenshots**
- Blink
![image](https://github.com/user-attachments/assets/fc9301c8-3108-441b-88a4-72bfe2823bba)
- Jellyfin Web
![image](https://github.com/user-attachments/assets/f1f941e3-13e0-4231-8687-674c2bcb00ad)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro (10.0.26100 Build 26100)
 - Version: 0.0.7-dev
 - Jellyfin Version: 10.10.3

**Comment by prayag17** [comment]
The image has not loaded here that is why you are not seeing it, simply reloading the app should fix this

**Comment by UniOnTheMap** [comment]
Nope, the thumbnail still doesn't show after a application restart.
